esphome:
  name: d1-mini-esp8266-relay-01
  friendly_name: d1-mini-esp8266-relay-01

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "[masked]"

ota:
  password: "[masked]"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "[masked]"
    password: "[masked]"

captive_portal:

switch:
  - platform: gpio
    name: "relay_01_switch"
    id: relay_01_switch
    pin: D1
    on_turn_on:
      - delay: 500ms
      - switch.turn_off: relay_01_switch

binary_sensor:
# Reports when the reed switch from GPIO04 to GND is sensing a magnet and the door is closed.
- platform: gpio
  pin:
    number: GPIO02
    mode: INPUT_PULLUP
    inverted: False
  name: "reed_01_switch"
  device_class: door
